version: "2"
services:
  mysql-master:
    image: mysql:8.0
    volumes:
      - mysql-replica-main:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/mysqldata-replica-main",
        "--binding-address: 0.0.0.0",
        "--log-bin=bin.log",
        "--server-id=1"
      ]
    environment:
      &mysql-default-environment
      MYSQL_ROOT_PASSWORD: *********
      MYSQL_DATABASE: adoption
      MYSQL_USER: replica
      MYSQL_PASSWORD: Password@123
    ports:
      - "3308:3306"
  mysql-slave:
    image: mysql:8.0
    volumes:
      - mysql-replica-read:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/mysqldata-replica-read",
        "--log-bin=bin.log",
        "--server-id=2"
      ]
    environment: *mysql-default-environment
    ports:
      - "3307:3306"

volumes:
  mysql-replica-main:
  mysql-replica-read:
